extraction:
  java:
    index:
      gradle:
        version: 6.8.1
      build_command:
        - ./gradlew --no-daemon -S lgtmCompile

path_classifiers:
  docs:
    - "LICENSE*"
    - "*.md"
    - "*.html"
  ci:
    - "appveyor.yml"
    - ".codecov.yml"
    - ".travis.yml"
    - ".circleci"
    - ".dependabot"
    - ".github"
    - ".lgtm.yml"
  generated:
    exclude: "**/*.java"
